name: prepare_deploy
description: Prepares deployment directory by syncing necessary files.

inputs:
  deployment_folder:
    description: Folder on the server to deploy to
    required: true
    type: string
  ssh_host:
    description: SSH host
    required: true
    type: string
  ssh_user:
    description: SSH user
    required: true
    type: string
  ssh_private_key:
    description: SSH private key
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Ensure deployment directory exists on server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          mkdir -p ~/${{ inputs.deployment_folder }}/${{ github.event.repository.name }}
