name: Rsync directory
on:
  workflow_call:
    inputs:
      source_folder:
        description: source_folder
        required: true
        type: string
      target_folder:
        description: target_folder
        required: true
        type: string

jobs:
  rsync-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure target directory exists on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ inputs.target_folder }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync folder
        run: rsync -avz --delete ${{ inputs.source_folder }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/${{ inputs.target_folder }}/

      - name: Fix permissions
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "chmod -R 755 ~/${{ inputs.target_folder }}"
